-- 코드를 입력하세요
SELECT B.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF A, ICECREAM_INFO B
WHERE A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY A.TOTAL_ORDER;


-- 위 아래 같은 코드 인데 WHERE 을 쓰냐 JOIN을 쓰냐 차이
SELECT 
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF A
    JOIN ICECREAM_INFO B
    ON A.FLAVOR = B.FLAVOR 
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;
