-- 코드를 입력하세요
--  "ANIMAL_ID" 열의 값 중에서 NULL이 아닌 행의 수를 세되, 만약 결과가 NULL이면 0으로 대체하여 "COUNT"라는 이름의 열로 반환
SELECT
    A.HOUR AS HOUR,
    COALESCE(COUNT(ANIMAL_ID), 0) AS COUNT
FROM
    (SELECT 0 AS HOUR UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
     UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14
     UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
     UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23) AS A
LEFT JOIN
    ANIMAL_OUTS ON A.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR;



WITH RECURSIVE hour_cte AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM hour_cte WHERE HOUR < 23
)
SELECT
    hour_cte.HOUR AS HOUR,
    COALESCE(COUNT(ANIMAL_ID), 0) AS COUNT
FROM
    hour_cte
LEFT JOIN
    ANIMAL_OUTS ON hour_cte.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY
    hour_cte.HOUR
ORDER BY
    hour_cte.HOUR;