-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
--WHERE (9 <= HOUR(DATETIME)) AND (HOUR(DATETIME) < 20)
GROUP BY HOUR
ORDER BY HOUR;
