-- 코드를 입력하세요
-- PRICE가 0보다 클 경우 ➡️ PRICE를 뒤에서부터 4개 삭제한다.
-- TRUNCATE(숫자,버릴 자릿수)
SELECT 
(CASE WHEN PRICE < 10000 THEN 0
ELSE TRUNCATE(PRICE, -4)
END) AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;


SELECT FLOOR(PRICE / 10000) * 10000 AS `PRICE_GROUP`, 
    COUNT(*) AS PRODUCTS
    FROM PRODUCT
GROUP BY `PRICE_GROUP`
ORDER BY `PRICE_GROUP`;