-- 코드를 입력하세요
SELECT A.APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT B ON A.PT_NO = B.PT_NO
JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND APNT_CNCL_YMD IS NULL AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;