-- 코드를 입력하세요
-- MySQL에서 CONTAINS는 해당 쿼리에서 사용할 수 있는 키워드가 아닙니다.
-- WHERE OPTIONS CONTAINS '네비게이션' 
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC;